export const routes = {
  login: '/login',
  schedule: '/schedule',
  agenda: '/agenda',
  calendar: '/calendar',
  money: '/money',
  insights: '/insights',
  history: '/history',
  about: '/about',
  profile: '/profile',
  settings: '/settings',
  quickMatch: '/matches/new/quick',
  fullMatch: '/matches/new',
  matchDetail: (matchId: string) => `/matches/${matchId}`,
  matchEdit: (matchId: string) => `/matches/${matchId}/edit`,
  tournaments: '/tournaments',
  tournamentNew: '/tournaments/new',
  tournamentDetail: (tournamentId: string) => `/tournaments/${tournamentId}`,
  tournamentEdit: (tournamentId: string) => `/tournaments/${tournamentId}/edit`,
} as const;
